### ISSUE TITLE
Add hiera support

### ISSUE THREAD

**Issue by kmarcroft** [chrekh/puppet-hosts#13]
Hi,

I like this module.
Though I would like to see hiera support for this module.
This example does not work:
```
hosts:
  enable_ipv4: true
  enable_ipv6: false
  lo_names: 
    - 'localhost'
    - 'localhost4'
    - 'localhost4.localdomain4'
```

Thanks
Kristian
